[package]
name = "sm-infra"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
keyring = { version = "3", features = ["apple-native", "windows-native", "linux-native"] }
sm-core = { path = "../sm-core" }
sm-services = { path = "../sm-services" }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
